# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import kingofsat.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(storage=kingofsat.storage.OverwriteStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kanali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='kingofsatTabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanal', models.CharField(db_index=True, max_length=225)),
                ('satelit', models.CharField(db_index=True, max_length=225)),
                ('polarizacija', models.CharField(db_index=True, max_length=225)),
                ('stupnjevi', models.CharField(db_index=True, max_length=225)),
                ('frekvencija', models.CharField(db_index=True, max_length=225)),
                ('sid', models.CharField(db_index=True, max_length=225)),
                ('paket', models.CharField(db_index=True, max_length=225)),
                ('dvb', models.CharField(db_index=True, max_length=225)),
                ('modulacija', models.CharField(db_index=True, max_length=225)),
                ('symbol_rate', models.CharField(db_index=True, max_length=225)),
                ('fec', models.CharField(db_index=True, max_length=225)),
                ('tid', models.CharField(db_index=True, max_length=225)),
                ('onid', models.CharField(db_index=True, max_length=225)),
                ('enkripcija', models.CharField(db_index=True, max_length=225)),
                ('tip', models.CharField(db_index=True, max_length=225)),
            ],
        ),
    ]
